packages:
  # CLI 工具链
  - 'cli'
  # 后端 API
  - 'server'
  # Admin SPA
  - 'web'
  # Desktop shell (Electron)
  - 'desktop'
  # 文档
  - 'docs'
  # 工具包
  - 'toolkit'
  # 官方主题包
  - 'themes'
  - 'themes/*'
  # 官方插件包
  - 'plugins'
  - 'plugins/*'
