name: Release Desktop

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-desktop:
    uses: ./.github/workflows/build-desktop-reusable.yml
    with:
      attach-to-github-release: true
